In [1]:
#NumPy

In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [28]:
## np means numerical python ie. nick name 

In [29]:
# Creating Arrays

In [30]:
sample_array = np.array([1,2,3,4])

In [31]:
sample_array

array([1, 2, 3, 4])

In [32]:
sample_array1 = np.array([1,2,3,4,5,6])

In [33]:
sample_array1

array([1, 2, 3, 4, 5, 6])

In [34]:
# 2D Array(a Matrix) with two rows and 2 columns

In [35]:
sample_array_2 = np.array([[1,2],[3,4]])

In [36]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [37]:
sample_array_3 = np.array([[11,22],[33,44]])

In [38]:
sample_array_3

array([[11, 22],
       [33, 44]])

In [39]:
# 3D Tensor(2 matrices, each with 2 rows and 2 columns )

In [42]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [43]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [53]:
sample_tensor_5 = np.array([[[1,33],[3,4]],[[5,6],[7,8]]])

In [55]:
sample_tensor_5

array([[[ 1, 33],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]]])

In [56]:
### Dimentions

In [63]:
## jr array 0 dimention cha asel tr tyala scal mhanayache
## 0-D Array(Scaller)5
##1-D Array(vector)[1,2,3,4]
## jr two dimentional array tr tyala Matrix mhanayache 
##2-D Arrya (Matrix)(rows and columns)
##3-D Array(Tensor) (Page,row,columns )

In [82]:
## Array properties

In [87]:
sample_array = np.array([[1,2,3],[5,6,7]])

In [88]:
sample_array

array([[1, 2, 3],
       [5, 6, 7]])

In [89]:
#Shape

In [90]:
sample_array.shape

(2, 3)

In [91]:
#dimentions

In [93]:
sample_array.ndim

2

In [94]:
## total elements

In [95]:
sample_array.size

6

In [106]:
# Data type

In [107]:
sample_array.dtype

dtype('int64')

In [108]:
sample_array = np.array([[[1,2,3],[43,56,78]],[[1,4,5,],[5,7,8]],[[3,7,9],[1,3,4]]])

In [109]:
sample_array

array([[[ 1,  2,  3],
        [43, 56, 78]],

       [[ 1,  4,  5],
        [ 5,  7,  8]],

       [[ 3,  7,  9],
        [ 1,  3,  4]]])

In [110]:
sample_array.shape

(3, 2, 3)

In [111]:
sample_array.dtype

dtype('int64')

In [112]:
sample_array.ndim

3

In [113]:
sample_array.size

18

In [114]:
# Special Array

In [116]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [122]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [124]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [126]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [133]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [134]:
#Indexing & Slicing

In [135]:
sample_array = np.array([10,20,30,40])

In [136]:
sample_array

array([10, 20, 30, 40])

In [137]:
sample_array[0]

np.int64(10)

In [138]:
sample_array[2]

np.int64(30)

In [139]:
sample_array[-1]

np.int64(40)

In [140]:
# Slicing

In [141]:
sample_array[1:3]

array([20, 30])

In [142]:
# Array Operation

In [143]:
a = np.array([1,2,3])

In [144]:
b = np.array([4,5,6])

In [146]:
a

array([1, 2, 3])

In [147]:
b

array([4, 5, 6])

In [145]:
a + b

array([5, 7, 9])

In [148]:
a - b

array([-3, -3, -3])

In [149]:
a * b

array([ 4, 10, 18])

In [150]:
a / b

array([0.25, 0.4 , 0.5 ])

In [161]:
a = np.array([22,11,33])

In [162]:
b = np.array([11,22,33])

In [163]:
a

array([22, 11, 33])

In [164]:
b

array([11, 22, 33])

In [165]:
a + b

array([33, 33, 66])

In [166]:
a -b

array([ 11, -11,   0])

In [167]:
a * b

array([ 242,  242, 1089])

In [168]:
a / b

array([2. , 0.5, 1. ])

In [187]:
# Mathematical Fuctions

In [188]:
sample_array = np.array([1,4,9])

In [189]:
sample_array

array([1, 4, 9])

In [190]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [191]:
sample_array1 = np.array([22,25,125])

In [192]:
sample_array1

array([ 22,  25, 125])

In [196]:
np.sqrt(sample_array1)

array([ 4.69041576,  5.        , 11.18033989])

In [197]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [198]:
np.exp(sample_array1)

array([3.58491285e+09, 7.20048993e+10, 1.93557604e+54])

In [199]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [200]:
# Satistical Functions

In [201]:
sample_array = np.array([1,2,3,4,5])

In [202]:
sample_array

array([1, 2, 3, 4, 5])

In [203]:
np.mean(sample_array)

np.float64(3.0)

In [204]:
np.median(sample_array)

np.float64(3.0)

In [207]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [208]:
np.min(sample_array)

np.int64(1)

In [209]:
np.max(sample_array)

np.int64(5)

In [210]:
# Reshaping Arrays

In [213]:
sample_array = np.arange(6)

In [215]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [216]:
reshape = sample_array.reshape(2,3)

In [217]:
reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [218]:
# flatterning

In [219]:
sample_array = np.array([[1,2],[3,4]])

In [221]:
sample_array

array([[1, 2],
       [3, 4]])

In [223]:
sample_array.flatten()

array([1, 2, 3, 4])

In [230]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [231]:
sample_tensor_3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [232]:
# joining Arrays

In [233]:
a = np.array([1,2,])

In [234]:
b = np.array([3,4])

In [235]:
a

array([22, 11, 33])

In [236]:
b

array([3, 4])

In [238]:
np.concatenate((a,b))

array([22, 11, 33,  3,  4])

In [239]:
#splitting Arrays

In [240]:
sample_array = np.array([1,2,3,4])

In [241]:
sample_array

array([1, 2, 3, 4])

In [242]:
np.array_split(sample_array,2)

[array([1, 2]), array([3, 4])]

In [247]:
# Random module

In [248]:
np.random.rand(3)

array([0.33668809, 0.57513444, 0.3544408 ])

In [249]:
np.random.randint(1,10,5)

array([6, 5, 9, 6, 6], dtype=int32)

In [250]:
sample_array = np.array([[1,2],[3,4]])

In [251]:
sample_array

array([[1, 2],
       [3, 4]])

In [252]:
np.sum(sample_array, axis=0)

array([4, 6])

In [253]:
np.sum(sample_array, axis=1)

array([3, 7])

In [254]:
# NaN & Missing Values

In [255]:
sample_array=np.array([1,np.nan,3])

In [256]:
sample_array

array([ 1., nan,  3.])

In [257]:
np.isnan(sample_array)

array([False,  True, False])

In [ ]:
# create 2 numpy array and per form element wise addition sub,mul,diviion,modulas operation

In [266]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8,])

In [267]:
a

array([1, 2, 3, 4])

In [268]:
b

array([5, 6, 7, 8])

In [269]:
a+b

array([ 6,  8, 10, 12])

In [270]:
a % b

array([1, 2, 3, 4])

In [271]:
a*b

array([ 5, 12, 21, 32])