In [1]:
### Section A — Exception Handling

In [2]:
# Q1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and TypeError separately. Use a finally block to print "Operation attempted" regardless of the outcome. Test it with valid numbers, division by zero, and a string input.

In [3]:
def safe_divide(a, b):
    try:
        result = a / b
        print("Result:", result)

    except ZeroDivisionError:
        print("Error: Cannot divide by zero.")

    except TypeError:
        print("Error: Invalid data type.")

    finally:
        print("Operation attempted")
safe_divide(10, 2)      # Valid input
safe_divide(10, 0)      # Division by zero
safe_divide(10, "2")    # String input

Result: 5.0
Operation attempted
Error: Cannot divide by zero.
Operation attempted
Error: Invalid data type.
Operation attempted


In [4]:
# Q2. Write a function validate_age(age) that raises a custom exception InvalidAgeError if age is negative or greater than 120. Catch this exception and print a user-friendly message. Test it with at least 3 different values.

In [5]:
class InvalidAgeError(Exception):
    pass

In [6]:
def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError("Age must be between 0 and 120.")
    print("Valid Age:", age)


# Test Cases
ages = [25, -5, 150]

for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print("Invalid Age Error:", e)

Valid Age: 25
Invalid Age Error: Age must be between 0 and 120.
Invalid Age Error: Age must be between 0 and 120.


In [7]:
#Q3. Write a program that repeatedly asks the user (using a loop with simulated inputs) to enter a number and divide 100 by it. Handle:
##ValueError if input is not a number ZeroDivisionError if input is zero Generic Exception for anything else

In [8]:
user_inputs = ['10', 'abc', '0', '5']

for value in user_inputs:
    try:
        num = int(value)
        result = 100 / num
        print(f"100 / {num} = {result}")

    except ValueError:
        print(f"ValueError: '{value}' is not a valid number.")

    except ZeroDivisionError:
        print("ZeroDivisionError: Cannot divide by zero.")

    except Exception as e:
        print("Error:", e)

100 / 10 = 10.0
ValueError: 'abc' is not a valid number.
ZeroDivisionError: Cannot divide by zero.
100 / 5 = 20.0


In [9]:
### Section B — NumPy

In [10]:
## Q4. Create a 1D NumPy array of integers from 1 to 20 and perform the following operations.

In [11]:
import numpy as np

# Create array from 1 to 20
arr = np.arange(1, 21)

# a) Reshape into 4x5 array
arr_2d = arr.reshape(4, 5)
print("4x5 Array:\n", arr_2d)

# b) Sum of rows and columns
print("\nRow Sum:", arr_2d.sum(axis=1))
print("Column Sum:", arr_2d.sum(axis=0))

# c) Elements greater than 10
print("\nElements > 10:", arr[arr > 10])

# d) Replace even numbers with -1
modified = arr.copy()
modified[modified % 2 == 0] = -1
print("\nModified Array:", modified)

4x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Row Sum: [15 40 65 90]
Column Sum: [34 38 42 46 50]

Elements > 10: [11 12 13 14 15 16 17 18 19 20]

Modified Array: [ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [12]:
# Q5. Create two NumPy arrays A and B and perform operations.

In [13]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# a) Element-wise operations
print("Addition:\n", A + B)
print("\nSubtraction:\n", A - B)
print("\nMultiplication:\n", A * B)

# b) Matrix Multiplication
print("\nMatrix Multiplication:\n", np.dot(A, B))

# c) Transpose of A
print("\nTranspose of A:\n", A.T)

# d) Determinant and Inverse
print("\nDeterminant of A:", np.linalg.det(A))
print("\nInverse of A:\n", np.linalg.inv(A))

Addition:
 [[ 6  8]
 [10 12]]

Subtraction:
 [[-4 -4]
 [-4 -4]]

Multiplication:
 [[ 5 12]
 [21 32]]

Matrix Multiplication:
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.0000000000000004

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
# Q6. Generate a NumPy array of 15 random integers between 1 and 100 (seed=42).

In [15]:
import numpy as np

np.random.seed(42)

arr = np.random.randint(1, 101, 15)

print("Array:", arr)

# a) Statistics
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))

# b) Descending Order
print("\nDescending Order:")
print(np.sort(arr)[::-1])

# c) Indices of 3 largest values
indices = np.argsort(arr)[-3:]
print("\nIndices of 3 Largest Values:", indices)

# d) Normalize values between 0 and 1
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print("\nNormalized Array:")
print(normalized)

Array: [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]
Mean: 58.06666666666667
Median: 72.0
Standard Deviation: 31.4843170836247
Minimum: 3
Maximum: 100

Descending Order:
[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

Indices of 3 Largest Values: [10  1 11]

Normalized Array:
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


In [16]:
#### Section C — Pandas

In [17]:
# Q7. Create a Pandas DataFrame from the dictionary below and perform the following.

In [18]:
import pandas as pd
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],"Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}
df = pd.DataFrame(data)

# a) First 3 rows and data types
print(df.head(3))
print(df.dtypes)

# b) Add Grade column
df["Grade"] = df["Score"].apply(
    lambda x: "A" if x >= 90 else ("B" if x >= 75 else "C")
)

# c) Sort by Score descending
print(df.sort_values(by="Score", ascending=False))

# d) Filter Department = AI
print(df[df["Department"] == "AI"])

    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
Name          object
Age            int64
Department    object
Score          int64
dtype: object
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


In [19]:
# Q8. Using the same DataFrame from Q7

In [20]:
import pandas as pd
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}
df = pd.DataFrame(data)
# a) Average score by department
print(df.groupby("Department")["Score"].mean())
# b) Row with highest score
print(df.loc[df["Score"].idxmax()])
# c) Rename Score to Marks
df.rename(columns={"Score": "Marks"}, inplace=True)
print(df)
# d) Drop Age column
df.drop("Age", axis=1, inplace=True)
print(df)

Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64
Name            Meera
Age                22
Department    Web Dev
Score              95
Name: 3, dtype: object
    Name  Age    Department  Marks
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79
3  Meera   22       Web Dev     95
4  Sahil   24  Data Science     67
    Name    Department  Marks
0  Aarav            AI     88
1  Priya  Data Science     92
2  Karan            AI     79
3  Meera       Web Dev     95
4  Sahil  Data Science     67


In [21]:
# Q9. Handle Missing Values
#Question Data data = {"Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
#"Price": [10, np.nan, 5, 8, np.nan],"Stock": [100, 50, np.nan, 30, 20]}

In [22]:
import pandas as pd
import numpy as np

data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# a) Missing values count
print(df.isnull().sum())

# b) Fill Price with mean
df["Price"].fillna(df["Price"].mean(), inplace=True)

# c) Drop rows where Stock is missing
df.dropna(subset=["Stock"], inplace=True)

# d) Save to CSV
df.to_csv("cleaned_products.csv", index=False)

print(df)

Product    0
Price      2
Stock      1
dtype: int64
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0


C:\Users\u\AppData\Local\Temp\ipykernel_12368\1336861366.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].mean(), inplace=True)


In [23]:
# Q10. Read CSV and Perform Operations

In [24]:
import pandas as pd
try:
    df = pd.read_csv("cleaned_products.csv")
    # a) Shape and columns
    print("Shape:", df.shape)
    print("Columns:", df.columns)
    # b) Add Total_Value column
    df["Total_Value"] = df["Price"] * df["Stock"]
    print(df)
    # c) Summary statistics
    print(df.describe())
except FileNotFoundError:
    print("File not found!")

Shape: (4, 3)
Columns: Index(['Product', 'Price', 'Stock'], dtype='object')
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
